import type { Metadata } from 'next';
import './globals.css';
import { AppContextProvider } from '@/contexts/AppContext';
import { Toaster } from '@/components/ui/toaster';
import Footer from '@/components/Footer';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'TokoBoost',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&family=PT+Sans:wght@400;700&display=swap"
          rel="stylesheet"
        />
        <script
          type="text/javascript"
          src="https://app.sandbox.midtrans.com/snap/snap.js"
          data-client-key={process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}
        ></script>
      </head>
      <body className="font-body antialiased flex flex-col min-h-screen">
        <AppContextProvider>
          <div className="flex-grow">{children}</div>
          <Footer />
          <Toaster />
        </AppContextProvider>
      </body>
    </html>
  );
}
